  backend:
    image: ubuntu-backend
    container_name: ubuntu_backend_1
    network_mode: 'host'
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_DB=distributed_computing
      - POSTGRES_USER=postgres
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    restart: always
