version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: gstd-worker
    restart: unless-stopped
    command: --node_id=${NODE_ID} --api=${API_URL:-https://app.gstdtoken.com/api/v1}
    environment:
      - NODE_ID=${NODE_ID}
      - API_URL=${API_URL:-https://app.gstdtoken.com/api/v1}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

